language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files

addons:
       apt:
         update: true
         sources:
           - sourceline: 'ppa:opencpu/imagemagick'
         packages:
           - libmagick++-dev

script:
  - Rscript -e "rmarkdown::render_site(output_format = 'bookdown::gitbook', encoding = 'UTF-8')"
  - Rscript -e "rmarkdown::render_site(output_format = 'bookdown::pdf_book', encoding = 'UTF-8')"

deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  github-token: $GITHUB_PAT  # Set in the settings page of your repository
  on:
    branch: master
