language: R
cache: packages
pandoc_version: 2.3.1
sudo: false

cache:
packages: yes
directories:
  - _bookdown_files

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  github-token: $TRAVIS_CI  # Set in the settings page
  on:
    branch: master
