# Les déterminants {#determinants}

## Le calcul d'un déterminant

Dans cette section, nous verrons la façon de calculer des déterminants de matrices $1\times 1$, $2\times 2$, pour ensuite voir une méthode générale pour calculer un déterminant d'une matrice $n\times n$.

```{definition, name="Le déterminant d'une matrice"}
Soit une matrice carrée $A$ de dimension $n\times n$. Le déterminant de $A$ est noté $\vert A\vert$ ou $\det (A)$.
```

### Le calcul d'un déterminant d'une matrice $1 \times 1$

```{definition}
Soit la matrice $A=[a_{1,1}]$. Le déterminant de $A$ est $\vert A\vert=a_{1,1}$. 
```

Dans le cas d'une matrice $1\times 1$, le déterminant de $A$ est tout simplement l'élément $a_{1,1}$ de la matrice.

```{example}
Trouvez le déterminant des matrices suivantes:
 
  a. $A=\vert 3\vert$
  a. $B=\vert -\pi\vert$

```


### Le calcul d'un déterminant d'une matrice $2\times 2$

```{definition}
Soit la matrice:
\begin{align*}
A = \begin{bmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end{bmatrix}
\end{align*}
Le déterminant de $A$ est donné par:
\begin{align*}
\vert A\vert &= \begin{vmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} & a_{2,2}
\end{vmatrix}
=
a_{1,1}\cdot a_{2,2}-a_{1,2}\cdot a_{2,1}
\end{align*}

```

```{example}
Trouvez le déterminant des matrices suivantes:

  a. $\begin{bmatrix}
3&-4\\
4&5\\
\end{bmatrix}$
  a. $\begin{bmatrix}
1&-2\\
-4&1\\
\end{bmatrix}$

```

### Le calcul d'un déterminant d'une matrice $n\times n$

Les deux sous-sections précédentes nous ont permises de constater que la calcul des déterminants de matrices $1\times 1$ ou $2\times 2$ se font de manière assez simple. L'intérêt d'être en mesure de calculer des déterminants de ce type est qu'il est toujours possible d'écrire le déterminant d'une matrice $n\times n$ en utilisant plusieurs déterminants de matrice $2\times 2$. Nous voulons donc maintenant étudier la façon d'écrire le déterminant d'une matrice $n\times n$ en plusieurs déterminants.

```{definition, name="Le mineur d'une matrice"}
Soit $A$ une matrice de dimension $n \times n$. Le mineur de la _ième_ ligne et de la _jième_ colonne, noté $M_{i,j}$, est le déterminant de la matrice résultante obtenue en enlevant la _ième_ ligne et la _jième_ colonne.
```

```{example}
Répondez aux questions suivantes:
  
  a. Trouvez le mineur $M_{1,2}$ de la matrice $A=\begin{bmatrix}
10&10&6\\
10&10&-8\\
-7&0&-2\\
\end{bmatrix}$.
  a. Trouvez le mineur $M_{2,3}$ de la matrice $B=\begin{bmatrix}
7&9&-5\\
9&3&1\\
-8&-8&10\\
\end{bmatrix}$.
  a. Trouvez le mineur $M_{2,2}$, sans le calculer, de la matrice $C=\begin{bmatrix}
10&0&9&-10\\
-7&6&6&7\\
10&-8&10&9\\
10&-2&3&4\\
\end{bmatrix}$.

```

```{remark}
Il est important de remarquer que le mineur d'une matrice de dimension $n\times n$ est toujours de dimension $(n-1)\times (n-1)$. Ceci signifie qu'un mineur diminue la dimension du déterminant que nous voulons calculer.
```

```{definition, name="Le cofacteur d'une matrice"}
Soit $A$ une matrice de dimension $n \times n$. Le cofacteur de la ième ligne et de la jième colonne, noté $C_{i,j}$, est donné par $(-1)^{i+j}M_{i,j}$, c'est-à-dire que le cofacteur est le mineur multiplié par un signe plus ou un signe moins.
```

Le terme $(-1)^{i+j}$ dans l'expression du cofacteur peut être soit de valeur $1$, soit de valeur $-1$. La façon la plus facile de se rappeler du signe est de se souvenir de la matrice ci-dessous.
\begin{align*}
\begin{bmatrix}
+ & - & + & \ldots \\
- & + & - & \ldots \\
+ & - & + & \ldots \\
\vdots & \vdots & \vdots & \ddots
\end{bmatrix}
\end{align*}
Nous remarquons que les signes alternent toujours avec un signe positif à l'élément situé à l'intersection de la première ligne et de la première colonne.

```{example}
À FAIRE...
```

```{definition, name="L'expansion par cofacteurs d'un déterminant"}
Soit $A$ une matrice de dimension $n \times n$. Le déterminant de $A$ est donné par:
  
\begin{align*}
\vert A\vert &= \sum_{k=1}^{n} a_{i,k}C_{i,k} \text{selon la ième ligne}\\
\vert A\vert &= \sum_{k=1}^{n} a_{k,j}C_{k,j} \text{selon la jième colonne}
\end{align*}

Pour être plus précis, l'expansion du déterminant de $A$ par la _ième_ ligne est donnée par:
\begin{align*}
\vert A\vert &= \sum_{k=1}^{n} a_{i,k}C_{i,k} = a_{i,1}C_{i,1}+a_{i,2}C_{i,2}+\ldots + a_{i,n}C_{i,n}
\end{align*}
Quant à elle, l'expansion du déterminant de $A$ par la _jième_ colonne est donnée par:
\begin{align*}
\vert A\vert &= \sum_{k=1}^{n} a_{k,j}C_{k,j} = a_{1,j}C_{1,j}+a_{2,j}C_{2,j}+\ldots + a_{n,j}C_{n,j}
\end{align*}


```

```{example}
Répondez aux questions suivantes:
  
  a. Trouvez le déterminant de la matrice suivante en utilisant l'expansion selon la première ligne.
\begin{align*}
A=\begin{bmatrix}
5&3&-10\\
5&-7&-5\\
-2&4&-10\\
\end{bmatrix}
\end{align*}
  a. Trouvez le déterminant de la matrice précédente en utilisant l'expansion selon la première colonne.


```

Comme le montre l'exemple précédent, nous pouvons calculer un déterminant en utilisant n'importe quelle ligne ou colonne de la matrice. Puisque le calcul du déterminant implique le produit d'un élément de la matrice par son mineur, cela indique que plus une ligne ou une colonne est composée de zéros, plus le calcul sera simple. L'exemple suivant clarifiera le tout.

```{example}
Trouvez le déterminant de la matrice suivante:
\begin{align*}
A = \begin{bmatrix}
-9&0&8\\
8&0&-3\\
9&-3&-8\\
\end{bmatrix}
\end{align*}
```

En général, l'expansion d'un déterminant à l'aide des cofacteurs permet de calculer un déterminant d'une matrice $n\times n$ à l'aide de $n$ déterminants de dimension $(n-1)\times (n-1)$. Nous devons ensuite effectuer l'expansion des déterminants de dimension $(n-1)\times (n-1)$ jusqu'à obtenir plusieurs déterminants de dimension $2\times 2$, qui se calculent facilement.

```{remark}
Pour simplifier le calcul d'un déterminant, il faut toujours en faire l'expansion selon la ligne ou la colonne qui contient le plus de zéros possibles.
```

```{example}
Calculez les déterminants des matrices suivantes:
  
  a. $A=\begin{bmatrix}
4&3&10&5\\
5&-7&-3&-5\\
-5&-8&2&0\\
4&0&-6&0\\
\end{bmatrix}$
  a. $B=\begin{bmatrix}
8&-5&9&-1&-4\\
10&7&-3&0&0\\
1&-5&-6&0&5\\
0&0&-5&0&0\\
-7&-5&2&0&0\\
\end{bmatrix}$


```

```{remark}
L'expansion d'un déterminant à l'aide des cofacteurs implique que le déterminant de n'importe quelle matrice triangulaire supérieure ou inférieure est le produit des éléments de sa diagonale principale.
```

```{example}
Calculez les déterminants des matrices suivantes.

  a. $A=\begin{bmatrix}
-9&6&1\\
0&9&-1\\
0&0&-10\\
\end{bmatrix}$
  a. $B=\begin{bmatrix}
-3&0&0&0&0&0&0&0\\
-7&4&0&0&0&0&0&0\\
6&5&10&0&0&0&0&0\\
-4&-1&-9&-9&0&0&0&0\\
1&-9&-1&-2&-8&0&0&0\\
-7&-6&-8&-5&8&-2&0&0\\
2&9&10&6&2&-9&9&0\\
-5&-7&-10&-1&1&-5&0&-5\\
\end{bmatrix}$

```

```{example}
Démontrez que $\det(I_n)=1$.
```

## Les propriétés des déterminants

Dans cette section, nous comprendrons et appliquerons les propriétés des déterminants et nous utiliserons celles-ci pour simplifier le calcul d'un déterminant.

L'expansion d'un déterminant à l'aide des cofacteurs requiert un grand nombre d'opérations et de temps, sauf si la matrice est relativement petite ou si elle possède un grand nombre de zéros. Il existe une meilleure méthode, basée sur l'élimination de Gauss. Premièrement, nous devons étudier certaines propriétés des déterminants.

### Les opérations élémentaires

```{theorem, name="Les propriétés de base des déterminants", label="proprietes-determinants"}
Les propriétés de base des déterminants sont:
  
  - La matrice $A$ et sa transposée on le même déterminant, c'est-à-dire $\det(A) = \det(A^T)$. Par exemple:
\begin{align*}
\begin{vmatrix}
a_1 & a_2 & a_3 \\
b_1 & b_2 & b_3 \\
c_1 & c_2 & c_3
\end{vmatrix}
=
\begin{vmatrix}
a_1 & b_1 & c_1 \\
a_2 & b_2 & c_2 \\
a_3 & b_3 & c_3
\end{vmatrix}
\end{align*}
  - Soit la matrice $B$ obtenue de la matrice $A$ en multipliant une de ses lignes (ou colonne) par un scalaire non-nul. Nous avons alors $\det(B)=k\det(A)$. Par exemple:
\begin{align*}
\begin{vmatrix}
a_1 & a_2 & a_3 \\
kb_1 & kb_2 & kb_3 \\
c_1 & c_2 & c_3
\end{vmatrix}
=
k\begin{vmatrix}
a_1 & a_2 & a_3 \\
b_1 & b_2 & b_3 \\
c_1 & c_2 & c_3
\end{vmatrix}
&
\phantom{aaa}
&
\begin{vmatrix}
a_1 & a_2 & ka_3 \\
b_1 & b_2 & kb_3 \\
c_1 & c_2 & kc_3
\end{vmatrix}
=k\begin{vmatrix}
a_1 & a_2 & a_3 \\
b_1 & b_2 & b_3 \\
c_1 & c_2 & c_3
\end{vmatrix}
\end{align*}
  - Soit la matrice $B_n$ obtenue de la matrice $A_n$ en faisant $B_n=kA_n$, où $k$ est un scalaire. Nous avons alors $\det(B)=k^n\det(A)$.
  - Soit la matrice $B$ obtenue de la matrice $A$ en interchangeant deux de ses lignes (ou colonnes). Nous avons alors $\det(B)=-\det(A)$. Par exemple:
\begin{align*}
\begin{vmatrix}
a_1 & a_2 & a_3 \\
b_1 & b_2 & b_3 \\
c_1 & c_2 & c_3
\end{vmatrix}
=
-\begin{vmatrix}
b_1 & b_2 & b_3 \\
a_1 & a_2 & a_3 \\
c_1 & c_2 & c_3
\end{vmatrix}
&
\phantom{aaa}
&
\begin{vmatrix}
a_1 & a_2 & a_3 \\
b_1 & b_2 & b_3 \\
c_1 & c_2 & c_3
\end{vmatrix}
=
-\begin{vmatrix}
a_1 & a_3 & a_2 \\
b_1 & b_3 & b_2 \\
c_1 & c_3 & c_2
\end{vmatrix}
\end{align*}
  - Si la matrice $A$ possède une ligne (ou colonne) composée uniquement de zéros, alors $\det(A)=0$. Par exemple:
\begin{align*}
\begin{vmatrix}
a_1 & a_2 & a_3 \\
0 & 0 & 0 \\
c_1 & c_2 & c_3
\end{vmatrix}
=
0
&
\phantom{aaa}
&
\begin{vmatrix}
a_1 & a_2 & 0 \\
b_1 & b_2 & 0 \\
c_1 & c_2 & 0
\end{vmatrix}
=0
\end{align*}
  - Si la matrice $A$ possède deux lignes (ou colonnes) identiques, alors $\det(A)=0$. Par exemple:
\begin{align*}
\begin{vmatrix}
a_1 & a_2 & a_3 \\
a_1 & a_2 & a_3 \\
c_1 & c_2 & c_3
\end{vmatrix}
=
0
&
\phantom{aaa}
&
\begin{vmatrix}
a_1 & a_2 & a_1 \\
b_1 & b_2 & b_1 \\
c_1 & c_2 & c_1
\end{vmatrix}
=0
\end{align*}
  - Soit la matrice $A$ telle que deux lignes (ou colonnes) sont des multiples l'une de l'autre. Nous avons alors $\det(A)=0$. Par exemple:
\begin{align*}
\begin{vmatrix}
a_1 & a_2 & a_3 \\
ka_1 & ka_2 & ka_3 \\
c_1 & c_2 & c_3
\end{vmatrix}
=
0
&
\phantom{aaa}
&
\begin{vmatrix}
a_1 & a_2 & ka_1 \\
b_1 & b_2 & kb_1 \\
c_1 & c_2 & kc_1
\end{vmatrix}
=0
\end{align*}
  - Soit la matrice $B$ obtenue de la matrice $A$ en additionnant un multiple d'une de ses ligne (ou colonne) à une \textbf{autre} ligne (ou colonne). Nous avons alors $\det(B)=\det(A)$. Par exemple:
\begin{align*}
\begin{vmatrix}
a_1 & a_2 & a_3 \\
b_1 & b_2 & b_3 \\
ka_1+c_1 & ka_2+c_2 & ka_3+c_3
\end{vmatrix}
&=
\begin{vmatrix}
a_1 & a_2 & a_3 \\
b_1 & b_2 & b_3 \\
c_1 & c_2 & c_3
\end{vmatrix}
\\
\begin{vmatrix}
a_1+ka_3 & a_2 & a_3 \\
b_1+kb_3 & b_2 & b_3 \\
c_1+kc_3 & c_2 & c_3
\end{vmatrix}
&=
\begin{vmatrix}
a_1 & a_2 & a_3 \\
b_1 & b_2 & b_3 \\
c_1 & c_2 & c_3
\end{vmatrix}
\end{align*}
  - Soit $A_n$ et $B_n$. Nous avons alors $\det(AB)=\det(A)\det(B)$.
  - Si la matrice $A$ possède une matrice inverse, alors $\det(A^{-1})=\dfrac{1}{\det(A)}$.

```

Les propriétés précédentes vont nous permettre de simplifier le calcul des déterminants un peu plus loin. Par contre, il n'existe pas de propriété simple pour l'addition de deux matrices.

```{example}
Soit les matrices 
$A=\begin{bmatrix}
7&-8\\
9&9\\
\end{bmatrix}$ et
$B=\begin{bmatrix}
3&-5\\
-8&1\\
\end{bmatrix}$.

  a. Calculez $\det(A)$
  a. Calculez $\det(B)$
  a. Calculez $\det(A)+\det(B)$
  a. Calculez $\det(A+B)$

```

L'exemple précédent nous indique que le déterminant d'une somme de matrices n'est pas nécessairement égal à la somme du déterminant de ces matrices.

```{remark}
En général, $\det(A+B)\neq \det(A)+\det(B)$.
```

```{example}
Soit la matrice suivante:
\begin{align*}
D_n =\begin{bmatrix}
1 & 1 & 1 & 1 & \ldots & 1 \\
1 & 2 & 2 & 2 & \ldots & 2 \\
1 & 2 & 3 & 3 & \ldots & 3 \\
1 & 2 & 3 & 4 & \ldots & 4 \\
\vdots &&&&& \vdots \\
1 & 2 & 3 & 4 & \ldots & n
\end{bmatrix}
\end{align*}

  a. Trouvez $\vert D_1\vert$.
  a. Trouvez $\vert D_2\vert$.
  a. Trouvez $\vert D_3\vert$.
  a. Trouvez $\vert D_n\vert$.

```

### Le calcul d'un déterminant à l'aide de la méthode de Gauss

À l'aide du théorème \@ref(thm:proprietes-determinants), nous pouvons remarquer que lors de l'élimination de Gauss, une opération du type:
\begin{align*}
	L_i + kL_j \rightarrow L_i 
\end{align*}
n'affecte pas le déterminant (en raison de la propriété $8$). Par contre, une opération du type:
\begin{align*}
	k_1L_i + k_2L_j \rightarrow L_i 
\end{align*}
multiplie le déterminant par $k_1$ (en raison de la propriété $2$). Nous allons utiliser ces connaissances pour simplifier le calcul d'un déterminant. En effet, nous avons vus que calculer le déterminant d'une matrice triangulaire supérieure consiste à multiplier tous les éléments de sa diagonale principale. De plus, la méthode d'élimination de Gauss permet de transformer une matrice en une matrice triangulaire supérieure. Nous allons utiliser ces deux éléments en conjonction.

```{example}
Trouvez le déterminant de la matrice suivante en effectuant la méthode d'élimination de Gauss.
\begin{align*}
A=\begin{bmatrix}
-8&10&-6\\
-8&2&-3\\
9&-9&7\\
\end{bmatrix}
\end{align*}
```

```{example}
Calculez les déterminants des matrices suivantes.

  a. $A=\begin{bmatrix}
7&9&-5\\
9&3&1\\
-8&-8&10\\
\end{bmatrix}$
  a. $B=\begin{bmatrix}
6&5&4&-3\\
-6&-5&-1&-5\\
4&-1&5&-5\\
4&-3&-4&5\\
\end{bmatrix}$


```

### Quelques preuves sur les déterminants

```{example}
Démontrez que $|A^k| = |A|^k$, où $k\in\mathbb{N}$.
```

```{example}
Démontrez que si $A$ est une matrice nilpotente d'ordre $2$, alors $\det(A)=0$.
```

```{example}
Démontrez que si $A$ est une matrice idempotente, alors $\det(A)=\{0,1\}$.
```

## La méthode de la matrice adjointe

Dans cette section, nous verrons une méthode permettant de trouver la matrice inverse d'une matrice à l'aide des déterminants.

```{definition, name="L'adjointe de la matrice $A$"}
Soit $A$ une matrice carrée de dimension $n \times n$. La matrice des cofacteurs est la matrice telle que l'entrée $(i,j)$ est le cofacteur $C_{i,j}$ de $A$. La transposée de la matrice des cofacteurs est nommée **l'adjointe** de $A$, notée $\text{Adj}(A)$ et est représentée par:
\begin{align*}
\text{Adj}(A) &= \begin{bmatrix}
C_{1,1} & C_{2,1} & \ldots & C_{n,1} \\
C_{1,2} & C_{2,2} & \ldots & C_{n,2} \\
\vdots & \vdots & \ddots & \vdots \\
C_{1,n} & C_{2,n} & \ldots & C_{n,n}
\end{bmatrix}
\end{align*}

```

```{example}
Trouvez la matrice des cofacteurs et la matrice adjointe de la matrice suivante:
\begin{align*}
A=\begin{bmatrix}
2&-1&2\\
3&2&-5\\
3&-4&-2\\
\end{bmatrix}
\end{align*}
```

```{theorem}
Soit $A$ une matrice carrée de dimension $n \times n$. Nous avons alors:
\begin{align*}
	A\text{Adj}(A) = \det(A)I_n = \text{Adj}(A)A
\end{align*}
```

```{theorem, label="adj-inverse"}
Soit $A$ une matrice possédant une matrice inverse. Nous avons alors:
\begin{align*}
A^{-1} = \dfrac{1}{\det(A)}\text{Adj}(A)
\end{align*}
```

```{example}
Trouvez la matrice inverse de la matrice $A$ suivante à l'aide du théorème \@ref(thm:adj-inverse):
\begin{align*}
A=\begin{bmatrix}
2&-1&2\\
3&2&-5\\
3&-4&-2\\
\end{bmatrix}
\end{align*}
```

## La méthode de Cramer

La méthode de Cramer permet de résoudre un système d'équations linéaires qui possède une solution unique et dont la matrice des coefficients est carrée. Elle permet également de ne trouver qu'une ou plusieurs des variables inconnues. Par contre, elle se base sur le calcul de plusieurs déterminants et en pratique, cette méthode est rarement utilisée. On lui préfère l'algorithme de Gauss, beaucoup plus rapide et efficace.

Soit un système d'équations linéaires de la forme $Ax=b$, où la matrice $A$ est carrée, avec:
\begin{align*}
A=\begin{bmatrix}
a_{1,1} & \ldots & a_{1,n} \\
\vdots & \ddots & \vdots \\
a_{n,1} & \ldots & a_{n,n}
\end{bmatrix}
\qquad
x=\begin{bmatrix}
x_1 \\
\vdots \\
x_n
\end{bmatrix}
\qquad
b=\begin{bmatrix}
b_1 \\
\vdots \\
b_n
\end{bmatrix}
\end{align*}

Soit $A_i$ la matrice obtenue de la matrice $A$ en remplaçant la colonne $i$ de la matrice $A$ par $b$, c'est-à-dire:
\begin{align*}
A_i=\begin{bmatrix}
a_{1,1} & \ldots & a_{1,i-1} & b_1 & a_{1,i+1} & \ldots & a_{1,n} \\
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots \\
a_{n,1} & \ldots & a_{n,i-1} & b_n & a_{n,i+1} & \ldots & a_{n,n}
\end{bmatrix}
\end{align*}

```{theorem, name="La méthode de Cramer"}
Si $\det(A)\neq 0$, le système $Ax=b$ possède une solution unique, donnée par:
\begin{align*}
x_1=\dfrac{\det(A_1)}{\det(A)}, x_2=\dfrac{\det(A_2)}{\det(A)}, \ldots , x_n=\dfrac{\det(A_n)}{\det(A)}
\end{align*}
```

```{example}
Utilisez la méthode de Cramer pour trouver la solution du système d'équations linéaires suivant:
\begin{align*}
\begin{array}{cccccccc}
&-x&+&y&-&z&=&2\\
&&&y&+&z&=&5\\
&x&&&+&z&=&-2\\
\end{array}
\end{align*}
```

```{example}
Supposez que $ad-bc\neq 0$. Utilisez la méthode de Cramer pour trouver la solution générale du système d'équations linéaires suivant:
\begin{align*}
\begin{array}{cccccc}
&ax&+&by&=&e\\
&cx&+&dy&=&f\\
\end{array}
\end{align*}
```

## Les applications du déterminant

Cette section contient de multiples applications du déterminant. Nous allons débuter en introduisant l'adjointe d'une matrice, qui permet, à l'aide du déterminant, de trouver la matrice inverse d'une matrice. Nous verrons ensuite la méthode de Cramer, qui permet de résoudre un système d'équations linéaires possédant une solution unique et qui permet de ne trouver la valeur que d'une seule variable à la fois. Nous introduirons ensuite des applications permettant de calculer l'aire d'un triangle, ou alors une applications permettant d'associer un polynôme à une matrice.

### L'aire d'un triangle à l'aide des déterminants

Dans cette sous-section, nous allons retrouver une formule impliquant un déterminant permettant de trouver l'aire d'un triangle dont nous connaissons les coordonnées des trois points le formant. La figure suivante nous aidera à retrouver la formule.

```{tikz, echo=FALSE, fig.cap = "L'aire d'un triangle avec un déterminant.", fig.ext = 'png', cache=TRUE, fig.align="center", out.width="50%"}
\begin{tikzpicture}

\draw[dashed] (0,0) rectangle (3,4);
\draw[thick, blue] (0,2)--(2,4)--(3,0)--cycle;
\node[left] at (0,2) {$(x_1,y_1)$};
\node[above] at (2,4) {$(x_2,y_2)$};
\node[right] at (3,0) {$(x_3,y_3)$};

\node[draw,circle,inner sep=1pt,fill] at (0,2) {};
\node[draw,circle,inner sep=1pt,fill] at (2,4) {};
\node[draw,circle,inner sep=1pt,fill] at (3,0) {};

\end{tikzpicture}
```

Remarquons que pour trouver la surface du triangle bleu, il est plus simple de trouver la surface totale du rectangle pointillé et d'ensuite enlever la surface des trois triangles rectangles $A$, $B$ et $C$.

Nous avons donc que la surface du rectangle est donnée par:
\begin{align*}
\text{Aire}_{\text{rectangle}} = (x_3-x_1)(y_2-y_3)
\end{align*}
La surface du triangle $A$ est donnée par:
\begin{align*}
\text{Aire}_{\Delta A} = \dfrac{1}{2}(x_2-x_1)(y_2-y_1)
\end{align*}
La surface du triangle $B$ est donnée par:
\begin{align*}
\text{Aire}_{\Delta B} = \dfrac{1}{2}(x_3-x_2)(y_2-y_3)
\end{align*}
La surface du triangle $C$ est donnée par:
\begin{align*}
\text{Aire}_{\Delta C} = \dfrac{1}{2}(x_3-x_1)(y_1-y_3)
\end{align*}

La surface du triangle en bleu est donc donnée par:
\begin{align*}
\text{Aire}_{\Delta} &= \text{Aire}_{\text{rectangle}}-\text{Aire}_{\Delta A}-\text{Aire}_{\Delta B}-\text{Aire}_{\Delta C} \\
&= (x_3-x_1)(y_2-y_3)-\dfrac{1}{2}(x_2-x_1)(y_2-y_1)-\dfrac{1}{2}(x_3-x_2)(y_2-y_3) \\
& \qquad \qquad -\dfrac{1}{2}(x_3-x_1)(y_1-y_3) \\
&= \dfrac{-x_2y_3+x_1y_3+x_3y_2-x_1y_2-x_3y_1+x_2y_1}{2} \qquad\text{(en simplifiant)} \\
&= \dfrac{1}{2}\left((x_3y_2-x_2y_3)-(x_3y_1-x_1y_3)+(x_2y_1-x_1y_2)\right)
\end{align*}

Étonnamment, la formule précédente peut être exprimée sous la forme du déterminant suivant:
\begin{align*}
\dfrac{1}{2}\begin{vmatrix}
1 & 1 & 1 \\
x_1 & x_2 & x_3 \\
y_1 & y_2 & y_3
\end{vmatrix}
\end{align*}
En fait, vous allez probablement remarquer que le déterminant suivant donne la formule de la surface d'un triangle à un signe près. Pour obtenir l'aire du triangle, il faut donc prendre la valeur absolue du déterminant précédent.

```{example}
Trouvez la surface du triangle dont les coordonnées sont $(-1,1)$, $(2,5)$ et $(10,2)$.
```

La formule obtenue pour l'aire d'un triangle peut nous aider à savoir si trois points sont colinéaires, c'est-à-dire si ces trois points se trouvent sur la même droite. En effet, si les trois points se trouvent sur la même droite, la surface du triangle sera nulle et donc le déterminant sera nul également.

### Le polynôme caractéristique d'une matrice

Le polynôme caractéristique d'une matrice est un polynôme qui renferme d'importantes propriétés de sa matrice. Entre autre, il renferme son déterminant, sa trace et ses valeurs propres. Bien que nous ne puissions voir les valeurs propres d'une matrice dans ce livre, celles-ci sont très importantes en algèbre linéaire. Le polynôme caractéristique est également utile dans un important théorème d'algèbre linéaire, le théorème de Cayley-Hamilton.

```{definition, name="Le polynôme caractéristique"}
Soit $A_n$ une matrice carrée. Le polynôme caractéristique de $A$, noté $p_{A_n}(t)$, est défini de la façon suivante:
\begin{align*}
p_{A_n}(t) = \det(tI_n-A_n)
\end{align*}
```

```{example}
Trouvez le polynôme caractéristique de la matrice suivante:
\begin{align*}
A=\begin{bmatrix}
2 & 1 \\
-1 & 0
\end{bmatrix}
\end{align*}
```

```{theorem, name="Quelques propriétés du polynôme caractéristique"}
Soit une matrice $A_n$ et $p_A(t)$ son polynôme caractéristique.

  - Le degré du polynôme est $n$.
  - Le coefficient de $t^n$ est $1$.
  - Le coefficient de $t^{n-1}$ est égal à la trace de la matrice $-A$, c'est-à-dire $\text{tr}(-A)=-\text{tr}(A)$.La trace d'une matrice correspond à la somme de ses éléments sur la diagonale principale.
  - Le coefficient constant de $p_A(t)$ est égal au déterminant de la matrice $-A$, c'est-à-dire $p_A(0)=\det(-A)=(-1)^n\det(A)$.


```

```{example}
Utilisez les propriétés précédentes pour écrire le polynôme caractéristique d'une matrice $A$ de dimension $2\times 2$.
```

```{example}
Le polynôme caractéristique d'un graphe est défini comme le polynôme caractéristique de sa matrice d'adjacence. En particulier, le polynôme caractéristique d'un graphe est un invariant du graphe. Dans cet exemple, nous étudierons en particulier le cas des graphes complets, notés $K_n$. Un graphe complet $K_n$ est un graphe possédant $n$ sommets tous reliés deux à deux par une arête. Voir la figure \@ref(fig:graphe-complet) pour quelques exemples de graphes complets. Vous pouvez vous rendre à la section \@ref(graphes) pour des définitions concernant les graphes.

Trouvez les polynômes caractéristiques des graphes suivants:

  a. $K_2$
  a. $K_3$
  a. $K_4$

```

```{tikz, echo=FALSE, fig.cap = "Quelques graphes complets.", fig.ext = 'png', cache=TRUE, fig.align="center", out.width="75%", label="graphe-complet"}
\begin{tikzpicture}

\begin{scope}
\def\N{2}
\foreach \i [evaluate={\j=\i+1;\k=\i+2}] in {1,2,...,\N}{
	\node[draw,circle,inner sep=1.5pt,fill, blue] at (\i/\N*360:1 cm) {};
	\draw (\i/\N*360:1 cm)--(\j/\N*360:1 cm);
	\draw (\i/\N*360:1 cm)--(\k/\N*360:1 cm);
}
\node[below,shift={(0,-0.5)}] at (270:1 cm) {$K_{\N}$};
\end{scope}

\begin{scope}[shift={(2.5,0)}]
\def\N{3}
\foreach \i [evaluate={\j=\i+1;\k=\i+2}] in {1,2,...,\N}{
	\node[draw,circle,inner sep=1.5pt,fill, blue] at (\i/\N*360:1 cm) {};
	\draw (\i/\N*360:1 cm)--(\j/\N*360:1 cm);
	\draw (\i/\N*360:1 cm)--(\k/\N*360:1 cm);
}
\node[below,shift={(0,-0.5)}] at (270:1 cm) {$K_{\N}$};
\end{scope}

\begin{scope}[shift={(5,0)}]
\def\N{4}
\foreach \i [evaluate={\j=\i+1;\k=\i+2}] in {1,2,...,\N}{
	\node[draw,circle,inner sep=1.5pt,fill, blue] at (\i/\N*360:1 cm) {};
	\draw (\i/\N*360:1 cm)--(\j/\N*360:1 cm);
	\draw (\i/\N*360:1 cm)--(\k/\N*360:1 cm);
}
\node[below,shift={(0,-0.5)}] at (270:1 cm) {$K_{\N}$};
\end{scope}

\begin{scope}[shift={(7.5,0)}]
\def\N{5}
\foreach \i [evaluate={\j=\i+1;\k=\i+2}] in {1,2,...,\N}{
	\node[draw,circle,inner sep=1.5pt,fill, blue] at (\i/\N*360:1 cm) {};
	\draw (\i/\N*360:1 cm)--(\j/\N*360:1 cm);
	\draw (\i/\N*360:1 cm)--(\k/\N*360:1 cm);
}
\node[below,shift={(0,-0.5)}] at (270:1 cm) {$K_{\N}$};
\end{scope}

\end{tikzpicture}
```











