# Les vecteurs de $\mathbb{R}^n$ {#vecteursRn}

Dans cette section, nous allons généraliser les notions de vecteurs dans $\mathbb{R}^2$ vues au chapitre \@ref(vecteursR2). Toutes les propriétés des vecteurs dans $\mathbb{R}^2$ ont leur analogue dans $\mathbb{R}^n$. De plus, nous nous attarderons plus particulièrement aux vecteurs dans $\mathbb{R}^3$ et à la façon de les représenter.

## Les vecteurs géométriques

```{definition,name="Les vecteurs de $\\mathbb{R}^n$"}
Un vecteur de $\mathbb{R}^n$, noté $\vec u$, est une matrice colonne composée de $n$ lignes.
\begin{align*}
\vec u &= \begin{bmatrix}
a_1 \\
a_2 \\
\vdots \\
a_n
\end{bmatrix}
\end{align*}
Parfois, pour économiser de l'espace, nous représentons un vecteur sur une ligne de la façon suivante:
\begin{align*}
\vec u &= (a_1,a_2,\ldots,a_n)
\end{align*}
```

Les vecteurs de $\mathbb{R}^n$ possèdent les mêmes propriétés que les vecteurs de $\mathbb{R}^2$.

### La représentation géométrique des vecteurs de $\mathbb{R}^3$

Comme pour les vecteurs de $\mathbb{R}^2$, il est possible de représenter graphiquement les vecteurs de $\mathbb{R}^3$. Pour ce faire, nous allons nous définir un système de coordonnées et nous allons voir comment représenter des points dans cet espace.

```{definition,name="Les coordonnées cartésiennes tridimensionnelles"}
Un système de coordonnées cartésiennes tridimensionnelles est formé d'une origine $O$, située à l'intersection des axes $x$, $y$ et $z$. Les axes $x$, $y$ et $z$ sont perpendiculaires entre eux. Les axes $y$ et $z$ sont l'analogue du plan cartésien dans l'espace en deux dimensions. L'axe des $x$ quant à lui doit être vu comme un axe qui "sort" de la page pour représenter la troisième dimension. La figure \@ref(fig:coordonnees-cartesiennes-R3) représente les coordonnées cartésiennes tridimensionnelles.
```

```{tikz,echo=FALSE,fig.align="center",,engine.opts = list(template = "resources/tikztemplate/mytikz.tex"),fig.cap="La représentation des coordonnées cartésiennes tridimensionnelles",label="coordonnees-cartesiennes-R3"}
\begin{tikzpicture}

\begin{axis}[
  unit vector ratio*=1 1 1,
  scale=4,
  view={120}{25},
  axis lines=center,
  xmin=-2,
  xmax=5.5,
  ymin=-2,
  ymax=5.5,
  zmin=-2,
  zmax=4.5,
  xlabel={$x$},
  ylabel={$y$},
  zlabel={$z$},
  xlabel style={below},
  ylabel style={right}
]

\tikzstyle{mystyle}=[draw,circle,inner sep=1pt,fill]
\coordinate [mystyle,label=above:{$P=(x_0,y_0,z_0)$}] (P) at (2,3,2.5);

\end{axis}

\end{tikzpicture}
```

Pour représenter un point à l'aide des coordonnées cartésiennes tridimensionnelles, nous devrons le faire à l'aide d'un 3-uplet, c'est-à-dire un point formé de trois coordonnées. 
\begin{align*}
P(x_1,y_1,z_1)
\end{align*}
Le premier élément du 3-uplet représente la position sur l'axes des $x$, le second élément du 3-uplet représente la position sur l'axes des $y$ et enfin le troisième élément du 3-uplet représente la position sur l'axes des $z$. En particulier, l'origine $O$ est représentée comme $O(0,0,0)$. Pour faciliter la visualisation, nous pouvons afficher des lignes pointillées pour situer le point sur les trois axes, comme à la figure \@ref(fig:position-point-R3).

```{tikz,echo=FALSE,fig.align="center",,engine.opts = list(template = "resources/tikztemplate/mytikz.tex"),fig.cap="La représentation d'un point en coordonnées cartésiennes tridimensionnelles",label="position-point-R3"}
\begin{tikzpicture}

\begin{axis}[
  unit vector ratio*=1 1 1,
  scale=2,
  view={120}{25},
  axis lines=center,
  xmin=-2,
  xmax=5.5,
  ymin=-2,
  ymax=5.5,
  zmin=-2,
  zmax=4.5,
  xlabel={$x$},
  ylabel={$y$},
  zlabel={$z$},
  xlabel style={below},
  ylabel style={right},
  ticks=none
]

\tikzstyle{mystyle}=[draw,circle,inner sep=1pt,fill]
\coordinate [mystyle,label=right:{$P=(x_0,y_0,z_0)$}] (P) at (2,3,3.5);

\draw[dashed] (2,0,0)--(2,3,0)--(2,3,3.5);
\draw[dashed] (2,0,0)--(2,0,3.5)--(2,3,3.5);
\draw[dashed] (0,0,0)--(0,0,3.5)--(2,0,3.5);
\draw[dashed] (2,3,0)--(0,3,0)--(0,3,3.5)--(2,3,3.5);
\draw[dashed] (0,0,3.5)--(0,3,3.5);

\node[above left] at (2,0,0) {$x_0$};
\node[above right] at (0,3,0) {$y_0$};
\node[above left] at (0,0,3.5) {$z_0$};

\end{axis}

\end{tikzpicture}
```

```{example}
Représentez les points $P(1,2,3)$, $Q(-2,-3,2)$ et $R(0,0,-4)$ dans le même espace cartésien.
```

Nous allons maintenant donner la définition d'un vecteur dans $\mathbb{R}^3$.

```{definition,name="Les vecteurs de $\\mathbb{R}^3$"}
Soit $A$ et $B$ deux points distincts représentés par des coordonnées cartésiennes tridimensionnelles. Le vecteur $\overrightarrow{AB}$ peut être représenté par une flèche ayant comme origine le point $A$ et comme arrivée le point $B$. L'emplacement du vecteur dans l'espace n'a pas d'importance. Deux déplacements de deux points d'origine distincts peuvent correspondre au même vecteur. Les seules informations importantes d'un vecteur sont:

  - Direction; Le segment de droite reliant le point $A$ au point $B$.
  - Sens; Il y a deux sens de parcours possible, du point $A$ au point $B$ ou l'inverse. Par convention, le sens du vecteur $\overrightarrow{AB}$ est du point $A$ vers le point $B$, tandis que le sens du vecteur $\overrightarrow{BA}$ est du point $B$ vers le point $A$.
  - Norme; La longueur du segment de droite reliant le point $A$ au point $B$.


```

SUITE...


## Les produits de vecteurs

Dans cette section, nous verrons le produit scalaire qui est définit pour les vecteurs de $\mathbb{R}^n$. Nous verrons ensuite le produit vectoriel qui n'est définit que pour les vecteurs $\mathbb{R}^3$. Enfin, nous discuterons du produit mixte, qui n'est en fait qu'un produit vectoriel suivi d'un produit scalaire.

### Le produit scalaire

Le produit scalaire est une opération mathématique qui à partir de deux vecteurs de même dimension retourne un nombre.

```{definition,name="Le produit scalaire"}
Soit $\overrightarrow{u}$ et $\overrightarrow{v}$ deux vecteurs de $\mathbb{R}^n$. Le produit scalaire de $\overrightarrow{u}$ et $\overrightarrow{v}$, noté $\overrightarrow{u}\cdot \overrightarrow{v}$, est donné par:
\begin{align*}
\overrightarrow{u} \cdot \overrightarrow{v} &= \sum_{k=1}^n u_kv_k
\end{align*}

Puisque nous avons définit les vecteurs comme des matrices colonnes, nous pouvons écrire le produit scalaire de la façon suivante:
\begin{align*}
\overrightarrow{u} \cdot \overrightarrow{v} &= \overrightarrow{u}^T \overrightarrow{v} = 
\begin{bmatrix}
u_1 & u_2 & \ldots & u_n
\end{bmatrix}
\begin{bmatrix}
v_1 \\
v_2 \\
\vdots \\
v_n
\end{bmatrix}
\end{align*}
où le produit entre les deux matrices est le produit **matriciel**.
```

```{example}
Soit les vecteurs suivants:
\begin{align*}
\overrightarrow{u}=\begin{bmatrix}
3\\
4\\
-4\\
5\\
\end{bmatrix}
\qquad 
\overrightarrow{v}=\begin{bmatrix}
-2\\
-4\\
-2\\
1\\
\end{bmatrix}
\qquad 
\overrightarrow{w}=\begin{bmatrix}
0\\
2\\
-4\\
0\\
\end{bmatrix}
\end{align*}
Trouvez les produits scalaires suivants:

  a. $\overrightarrow{u}\cdot\overrightarrow{v}$
  a. $\overrightarrow{u}\cdot\overrightarrow{w}$
  a. $\overrightarrow{v}\cdot\overrightarrow{w}$

```

L'exemple précédent nous montre que le produit scalaire de deux vecteurs peut être positif, négatif ou nul.

Il est possible de définir une quantité très importante des vecteurs à l'aide du produit scalaire. En effet, la norme d'un vecteur est donnée par:
\begin{align*}
\lVert\overrightarrow{u}\rVert &= \sqrt{u_1^2+u_2^2+\ldots +u_n^2} \\
&= \sqrt{\sum_{k=1}^n u_k^2} \\
&= \sqrt{\overrightarrow{u} \cdot \overrightarrow{u}} \qquad \text{(par définition du produit scalaire)}
\end{align*}}
Nous pouvons également écrire $\lVert\overrightarrow{u}\rVert^2=\overrightarrow{u} \cdot \overrightarrow{u}$.

Nous définissons également la distance euclidienne $d$ entre deux vecteurs $\overrightarrow{u}$ et $\overrightarrow{v}$ de la façon suivante:
\begin{align*}
d = \lVert\overrightarrow{u}-\overrightarrow{v}\rVert
\end{align*}

Le produit scalaire possède plusieurs propriétés que nous allons énumérer dans le théorème qui suit.

```{theorem,name="Les propriétés du produit scalaire"}
Soit $\overrightarrow{u}$, $\overrightarrow{v}$ et $\overrightarrow{w}$ trois vecteurs de $\mathbb{R}^n$ et $c$ un scalaire.

  1. $\overrightarrow{u}\cdot \overrightarrow{v} = \overrightarrow{v}\cdot \overrightarrow{u}$
  1. $\overrightarrow{u}\cdot (\overrightarrow{v}+\overrightarrow{w})=\overrightarrow{u}\cdot \overrightarrow{v}+\overrightarrow{u}\cdot \overrightarrow{w}$
  1. $c(\overrightarrow{u}\cdot \overrightarrow{v})=(c\overrightarrow{u})\cdot \overrightarrow{v}=\overrightarrow{u}\cdot (c\overrightarrow{v})$
  1. $\overrightarrow{u}\cdot \overrightarrow{u} \geq 0$
  1. $\overrightarrow{u}\cdot \overrightarrow{u} =0$ si et seulement si $\overrightarrow{u}=\overrightarrow{0}$


```

```{definition,name="L'interprétation géométrique du produit scalaire"}
Soit $\overrightarrow{u}$ et $\overrightarrow{v}$ deux vecteurs de $\mathbb{R}^n$. Le produit scalaire de $\overrightarrow{u}$ et $\overrightarrow{v}$ est donné par:
\begin{align*}
\overrightarrow{u} \cdot \overrightarrow{v} &= \lVert\overrightarrow{u}\rVert\lVert\overrightarrow{v}\rVert\cos(\theta)
\end{align*}
où $\lVert\overrightarrow{u}\rVert$ est la norme du vecteur $\overrightarrow{u}$, $\lVert\overrightarrow{v}\rVert$ est la norme du vecteur $\overrightarrow{v}$ et $\theta$ est l'angle entre les vecteurs $\overrightarrow{u}$ et $\overrightarrow{v}$.
```

```{example}
Soit $\overrightarrow{u}$ et $\overrightarrow{v}$ deux vecteurs de $\mathbb{R}^n$. Démontrez l'égalité suivante:
\begin{align*}
\lVert\overrightarrow{u}+\overrightarrow{v}\rVert^2=\lVert\overrightarrow{u}\rVert^2+\lVert\overrightarrow{v}\rVert^2+2(\overrightarrow{u}\cdot \overrightarrow{v})
\end{align*}
```

```{example}
Soit $\overrightarrow{u}$ et $\overrightarrow{v}$ deux vecteurs de $\mathbb{R}^n$. Démontrez l'égalité suivante:
\begin{align*}
\lVert\overrightarrow{u}-\overrightarrow{v}\rVert^2=\lVert\overrightarrow{u}\rVert^2+\lVert\overrightarrow{v}\rVert^2-2(\overrightarrow{u}\cdot \overrightarrow{v})
\end{align*}
```

### Des applications

```{example}
BAG OF WORDS MODEL...
```


















