## Les plans de l'espace

Dans cette section, nous allons définir les équations qui nous permettent de décrire les plans de l'espace. Nous étudierons également la distance entre un point et un plan, la distance entre deux plans et la position relative de deux plans.

### L'équation vectorielle du plan de l'espace

Il est possible de trouver une équation vectorielle du plan de l'espace, tout comme nous avons trouvé une équation vectorielle pour une droite de l'espace.

Soit $P_0$ un point faisant partie du plan et $\vec u$, $\vec v$ deux vecteurs non parallèles se trouvant dans le plan. Nous voulons trouver une équation nous permettant de trouver un point $P$ faisant partie du plan. À l'aide de la figure \@ref(fig:equations-plans-vectorielles), nous pourrons trouver cette équation.

```{tikz,echo=FALSE,fig.align="center",out.width="75%",fig.cap="La représentation des équations d'un plan sous forme vectorielle.",label="equations-plans-vectorielles"}
\begin{tikzpicture}

\draw[fill=blue,fill opacity=0.5] (0,3)--(-3,0)--(2,-1)--(5,2)--cycle;

\draw[->,>=stealth] (-1,0)--(4,0) node[right] {$y$};
\draw[->,>=stealth] (0,-1)--(0,4) node[above] {$z$};
\draw[->,>=stealth] (0.5,0.5)--(-2,-2) node[below left] {$x$};

\draw[->,>=stealth,very thick] (0,0)--(1,1);
\draw[->,>=stealth,red,very thick] (1,1)--(2,2) node[right] {$\vec u$};
\draw[->,>=stealth,red,very thick] (1,1)--(1.5,-0.5) node[right] {$\vec v$};
\draw[->,>=stealth,very thick] (1,1)--(3,1.5) node[right] {$\vec a$};

\tikzstyle{mystyle}=[draw,circle,inner sep=1pt,fill]
\coordinate [mystyle,label=above left:$P_0$] (P0) at (1,1);

\end{tikzpicture}
```

Dans la version en ligne de ce document, vous trouverez ci-dessous une version interactive d'un plan sous forme vectorielle.

<iframe scrolling="no" title="Plan de l'espace" src="https://www.geogebra.org/material/iframe/id/et4mk7ev/width/700/height/500/border/888888/sfsb/true/smb/false/stb/false/stbh/false/ai/false/asb/false/sri/true/rc/false/ld/false/sdz/true/ctl/false" width="700px" height="500px" style="border:0px;"> </iframe>

Soit $P$ un point quelconque du plan. Nous pouvons dire que:
\begin{align*}
\overrightarrow{OP} &= \overrightarrow{OP_0} + \vec a
\end{align*}
Remarquons que le vecteur $\vec a$ peut s'écrire comme une combinaison linéaire des vecteurs $\vec u$ et $\vec v$, c'est-à-dire que:
\begin{align*}
\vec a &= s\vec u + t \vec v
\end{align*}
où $s,t\in\mathbb{R}$. Nous avons donc:
\begin{align}
\overrightarrow{OP} &= \overrightarrow{OP_0} + \vec a \\
&= \overrightarrow{OP_0} + s\vec u + t \vec v
(\#eq:equation-vectorielle-plan)
\end{align}
où $s,t\in\mathbb{R}$. L'équation \@ref(eq:equation-vectorielle-plan) est l'équation vectorielle d'un plan.

```{definition,name="L'équation vectorielle d'un plan de l'espace"}
Nous pouvons maintenant donner la définition de l'équation vectorielle d'un plan de l'espace.
Soit $P_0=(x_0,y_0,z_0)$ un point d'une droite et $u=[u_1,u_2,u_3]$ et $v=[v_1,v_2,v_3]$ deux vecteurs directeurs de ce plan. L'équation vectorielle de ce plan est donnée par:
\begin{align*}
\overrightarrow{r} &= \overrightarrow{r_0}+s\overrightarrow{u}+t\overrightarrow{v} \\
[x,y,z] &= [x_0,y_0,z_0]+s[u_1,u_2,u_3]+t[v_1,v_2,v_3]
\end{align*}
où $s,t\in\mathbb{R}$.
```

Les paramètres $s$ et $t$ nous permettent d'obtenir tous les points du plan par combinaison linéaire.

Nous pouvons définir de "nouvelles" équations de droites à l'aide de la définition de l'équation vectorielle d'une droite.

```{definition,name="Les équations paramétriques d'un plan de $\\mathbb{R}^3$"}
Soit $P_0=(x_0,y_0,z_0)$ un point d'une plan et $u=[u_1,u_2,u_3]$, $v=[v_1,v_2,v_3]$ les vecteurs directeurs de ce plan. Nous savons que l'équation vectorielle de ce plan est donnée par:
\begin{align*}
\overrightarrow{r} &= \overrightarrow{r_0}+s\overrightarrow{u}+t\overrightarrow{v} \\
[x,y,z] &= [x_0,y_0,z_0]+s[u_1,u_2,u_3]+t[v_1,v_2,v_3]
\end{align*}
où $s,t\in\mathbb{R}$.

Puisque l'équation vectorielle d'un plan correspond à une égalité entre deux vecteurs et que deux vecteurs sont égaux lorsque leurs composantes respectives sont égales, nous pouvons écrire:
\begin{align*}
x &= x_0 + su_1 + tv_1 \\
y &= y_0 + su_2 + tv_2 \\
z &= z_0 + su_3 + tv_3 \\
\end{align*}
où $s,t\in\mathbb{R}$. Les équations précédentes sont nommées les équations paramétriques d'un plan de $\mathbb{R}^3$.
```

Le prochain exemple permettra de voir comment nous pouvons trouver l'équation d'une droite et ensuite l'utiliser pour trouver certains points de la droite.

```{example}
Soit les points $A=(3,2,1)$, $B=(-4,0,2)$ et $C=(1,1,2)$ faisant partie du plan $D$.

  a. Trouvez deux vecteurs directeurs du plan $D$.
  a. Trouvez l'équation vectorielle du plan $D$.
  a. Utilisez l'équation trouvée en b) pour trouver deux points du plan $D$ autres que $A$, $B$ et $C$.
  a. Est-ce que le point $E=(-8,1,-1)$ fait partie du plan $D$?
  a. Est-ce que le point $F=(-15,-2,1)$ fait partie du plan $D$?

```

### L'équation normale du plan de l'espace

Il est possible de définir une autre équation du plan, qui elle nous sera davantage utile. Cette définition s'appuie sur le vecteur normal au plan.

```{definition,name="Le vecteur normal au plan"}
Soit un plan $D$. Un vecteur normal au plan, noté $\vec n$, est un vecteur tel que tous les vecteurs se trouvant sur le plan sont perpendiculaires à $\vec n$.
```

Nous allons maintenant utiliser le vecteur normal au plan pour définir l'équation normale du plan de l'espace. Soit un plan $P$ et un vecteur $\vec n=[a,b,c]$ normal à ce plan. Soit aussi un point $P(x_0,y_0,z_0)$ connu faisant partie du plan et un point $Q(x,y,z)$ un point quelconque du plan. Nous utiliserons la figure \@ref(fig:equation-plans-normale) pour trouver l'équation normale du plan.

```{tikz,echo=FALSE,fig.align="center",out.width="75%",fig.cap="La représentation de l'équation normale d'un plan.",label="equation-plans-normale"}
\begin{tikzpicture}

\draw[fill=blue,fill opacity=0.5] (0,3)--(-3,0)--(2,-1)--(5,2)--cycle;

\draw[->,>=stealth] (-1,0)--(4,0) node[right] {$y$};
\draw[->,>=stealth] (0,-1)--(0,4) node[above] {$z$};
\draw[->,>=stealth] (0.5,0.5)--(-2,-2) node[below left] {$x$};

\draw[->,>=stealth,very thick,red] (0.75,0.5)--(0.75,3.5) node[left] {$\vec n$}; 
\draw[->,>=stealth,very thick] (0.75,0.5)--(2.5,2);
\draw[thick] (0.75,0.8)--(0.95,1)--(0.95,0.65);

\tikzstyle{mystyle}=[draw,circle,inner sep=1pt,fill]
\coordinate [mystyle,label=below right:{$P_0(x_0,y_0,z_0)$}] (P0) at (0.75,0.5);
\coordinate [mystyle,label=below right:{$Q(x,y,z)$}] (Q) at (2.5,2);

\end{tikzpicture}
```

Dans la version en ligne de ce document, vous trouverez ci-dessous une version interactive d'un plan sous forme normale.

<iframe scrolling="no" title="Plan de l'espace normal" src="https://www.geogebra.org/material/iframe/id/y64rcr4s/width/700/height/571/border/888888/sfsb/true/smb/false/stb/false/stbh/false/ai/false/asb/false/sri/true/rc/false/ld/false/sdz/true/ctl/false" width="700px" height="571px" style="border:0px;"> </iframe>

Puisque le vecteur normal $\vec n$ est perpendiculaire à tous les vecteurs se trouvant sur le plan, il est en particulier perpendiculaire au vecteur $\overrightarrow{PQ}$. Si nous définissons le vecteur $\vec p = \overrightarrow{OP}$ et le vecteur $\vec x=\overrightarrow{OQ}$, nous avons que:
\begin{align}
\vec n \cdot (\vec x - \vec p) &= 0 \qquad\text{(car $\vec n \perp (\vec x - \vec p)$)}
(\#eq:equation-plans-normale)
\end{align}
L'équation \@ref(eq:equation-plans-normale) représente l'équation normale d'un plan.

```{definition,name="L'équation normale d'un plan"}
Soit un plan $P$. Soit un vecteur normal à ce plan $\vec n=[a,b,c]$ et un point de ce plan $P(x_0,y_0,z_0)$ connu. L'équation normale du plan est donnée par:
\begin{align*}
\vec n \cdot (\vec x - \vec p) &= 0 \\
[a,b,c] \cdot [x-x_0,y-y_0,z-z_0] &= 0 \\
a(x-x_0)+b(y-y_0)+c(z-z_0) &= 0
\end{align*}

Nous pouvons également écrire l'équation précédente sous une forme légèrement différente:
\begin{align*}
a(x-x_0)+b(y-y_0)+c(z-z_0) &= 0 \\
ax-ax_0+by-by_0+cz-cz_0 &= 0 \\
ax+by+cz-\underbrace{(ax_0+by_0+cz_0)}_{=d} &= 0 \\
ax+by+cz-d &= 0
\end{align*}
```

```{remark}
Nous utiliserons habituellement l'équation $a(x-x_0)+b(y-y_0)+c(z-z_0) = 0$ comme équation normale du plan, car elle permet de trouver immédiatement le point utilisé comme faisant partie du plan.
```

Remarquons que dans l'équation normale d'un plan n'apparaissent pas de paramètres $s$ et $t$ comme dans l'équation vectorielle d'un plan. L'équation normale consiste en fait en une équation linéaire possédant trois inconnues. Comme nous l'avons vu, une telle équation possède deux paramètres libres. Ceci signifie que pour trouver un point se trouvant sur le plan, il suffit de poser deux des trois inconnues égales à une certaine valeur et de résoudre l'équation ainsi formée.

```{example}
Soit le plan $P$ donné par l'équation suivante:
\begin{align*}
3x+2y-z+4 &= 0
\end{align*}
Trouvez deux points se trouvant sur la plan $P$.
```

```{example}
Trouvez l'équation du plan $P$ ayant comme vecteur normal $\vec n=[3,4,2]$ et passant par le point $P(1,2,3)$.
```

```{example}
Trouvez l'équation normale du plan $P$ passant par les points $A(-2,1,3)$, $B(3,3,1)$ et $C(5,-4,-2)$.
```

### Les positions relatives de plans de l'espace

Nous allons maintenant étudier les positions relatives de deux plans. Soit deux plans dans l'espace, nous désirons savoir s'il s'intersecte ou non.

Soit deux plans de $\mathbb{R}^3$:
\begin{align*}
P_1 :& a(x-x_1)+b(y-y_1)+c(z-z_1)=0 \\
P_2 :& d(x-x_2)+e(y-y_2)+f(z-z_2)=0
\end{align*}
Si les deux plans se croisent, alors le système d'équations linéaires possédera une solution:
\begin{align*}
ax+by+cz &= -(ax_1+by_1+cz_1) \\
dx+ey+fz &= -(dx_2+ey_2+fz_2)
(\#eq:equation-position-relative-plan)
\end{align*}

Le système d'équations linéaires \@ref(eq:equation-position-relative-plan) possède deux équations et trois inconnues, $x$, $y$ et $z$. Ce système peut posséder deux types de solutions:

  1. Aucune solution, ce qui signifie que les plans ne se croisent jamais.
  1. Une infinité de solutions, ce qui signifie que les plans se croisent.

```{remark}
Il est impossible que le système d'équations linéaires possède une unique solution car nous avons davantage d'inconnues que d'équations.
```

De plus, dans $\mathbb{R}^3$, deux plans peuvent se retrouver dans trois situations différentes.

  1. Deux plans peuvent être parallèles confondus, c'est-à-dire qu'ils forment un seul et même plan.
  1. Deux plans peuvent être parallèles distincts, c'est-à-dire qu'ils ne se touchent jamais.
  1. Deux plans peuvent être non-parallèles, c'est-à-dire que leur intersection est une droite de $\mathbb{R}^3$.









